### PR TITLE
Login page

### PR DESCRIPTION
**Pull request by rebekahpidgeon**
Login page completed and can be navigated to using its link. https://www.disneyplus.com/en-gb/login - reference I used for designing this page

### CODE REVIEW

**Comment by apu52** [comment]
@rebekahpidgeon Can you please share some SS or describe your work more precisely ??

**Comment by rebekahpidgeon** [comment]
Of course! I have attached a screenshot of the login page 

image

**Comment by rebekahpidgeon** [comment]
Here a few more SS with a demonstration of some of the functionality

Focus on the email address field:
image

Hover on sign up button:
image

Hover on continue button:
image

**Comment by 5h0ov** [comment]
@rebekahpidgeon  hmm looks great! Thanks for contributing!

**Comment by apu52** [comment]
@rebekahpidgeon  great work

**Pull request merged**
